language: ruby
rvm:
  - 2.3.1
env: SECRET_KEY_BASE=859384 RUN_SLOW_TESTS=true DONT_RUN_DOCKER_TESTS=true

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
