---
dependencies:
  - { role: docker-server }
  - { role: nginx-passenger }
  - { role: ruby-2.0.0-p353 }
  - { role: mysql }
  - { role: backups }
  - { role: redis }
  - { role: newrelic-sysmond }
  - { role: discourse }
  - { role: mitmproxy }
  - role: f500.elasticsearch
    elasticsearch_network_host: localhost
