- name: Make sure that pip is installed
  apt: pkg=python-pip

# Newer version of docker-py causes issues. See
# https://github.com/ansible/ansible-modules-core/issues/1227
- name: Install requirement for ansible docker
  pip:
    name: docker-py
    version: 1.1.0

# TODO: Log back to syslog on machine
- name: Install docker container for mitmdump
  docker:
    name: mitmdump2
    image: openaustralia/morph-mitmdump
    state: started
    restart_policy: always
    pull: always
    # We attach the networking of this container to the host. This is necessary
    # because otherwise traffic would get redirected to the container, would
    # get proxied and a new request would come from this container which would
    # promptly get redirected back to the container in a painful infinite loop
    # This is a good reference for the issues:
    # https://github.com/jpetazzo/squid-in-a-can
    net: host
    env:
      MORPH_URL: "{{ morph_url }}"
      MITMPROXY_SECRET: "{{ mitmproxy_secret }}"
