- name: Install python
  apt: pkg=python
- name: Install development headers for python
  apt: pkg=python-dev
- name: Install build-essential
  apt: pkg=build-essential
- name: Install libxslt1-dev
  apt: pkg=libxslt1-dev
- name: Install pip (required to install mitmproxy)
  apt: pkg=python-pip
- name: Install version 0.12 of mitmproxy
  pip:
    name: mitmproxy
    version: 0.12
